### PR TITLE
Updated Screenshots

### PR DESCRIPTION
**Pull request by yschimke**
#fixes https://github.com/android/wear-os-samples/issues/216

### CODE REVIEW

**Comment by yschimke** [comment]
Readme preview https://github.com/android/wear-os-samples/blob/2b36b81f590e52d00d0a3394bc0ffec71d61199d/ComposeAdvanced/README.md

**Comment by yschimke** [comment]
@shumelchyk I took them before I realised about the frame, do you want me to capture with frames.  I prefer these, but defer to your wisdom.

**Review by shumelchyk — APPROVED** [review]
LGTM, I think it's ok to have screenshots without watch frame (as default ones done on emulator).
Few comments (not critical for this PR):
- For watch list screenshot - is the latest version with removed paddings between list items?
- Can we add screenshots for slider and stepper?

**Comment by shumelchyk** [comment]
So extra padding is landing in #336, maybe worth grabbing a fresh screenshot afterwards

**Pull request merged**
