### PR TITLE
[AlwaysOn] Use Gradle Managed Devices for testing

### PR DESCRIPTION
**Pull request by alexvanyo**
Reopening #173 with a rebased PR.

This updates AGP to 7.3.0, so no plans to merge until that is stable, but we can exercise GitHub Actions to check if everything works.

### CODE REVIEW

**Comment by yschimke** [comment]
```
Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'abi' for object of type com.android.build.gradle.internal.dsl.ManagedVirtualDevice.
	at org.gradle.internal.metaobject.AbstractDynamicObject.setMissingProperty(AbstractDynamicObject.java:121)
	at org.gradle.internal.metaobject.ConfigureDelegate.setProperty(ConfigureDelegate.java:104)
	at build_ber2wmv9y9d38v08e0nzlfzhd$_run_closure1$_closure8$_closure12$_closure13.doCall(/home/runner/work/wear-os-samples/wear-os-samples/AlwaysOnKotlin/views/build.gradle:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by yschimke** [comment]
abi removed https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-api/src/main/java/com/android/build/api/dsl/ManagedVirtualDevice.kt;bpv=1

**Comment by yschimke** [comment]
Ooooffff...

https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/options/BooleanOption.kt;l=158?q=allowOldApiLevelDevices

Caused by: org.gradle.api.GradleException: API level 26 and lower is currently not supported for Gradle Managed devices.
Your current configuration requires API level 26.
While it's not recommended, you can use API levels 26 and lower by adding
android.experimental.testOptions.managedDevices.allowOldApiLevelDevices=true
to your gradle.properties file.

**Comment by yschimke** [comment]
Ooooffff....

https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/ManagedDeviceSetupTask.kt;l=123?q=ManagedDeviceSetupTask

    private fun assertNoWearTvOrAuto() {
        // Since we presently don't support wear and tv devices, we need to check
        // if the developer is trying to use an image from those sources.
        if (isWearTvOrAutoSource(systemImageVendor.get())) {
            error(
                """
                    ${managedDeviceName.get()} has a systemImageSource of ${systemImageVendor.get()}.
                    Wear, TV and Auto devices are presently not supported with Gradle Managed Devices.
                """.trimIndent()
            )
        }

        // Or is attempting to use a wear, tv, or automotive device profile.
        if (isWearTvOrAutoDevice(hardwareProfile.get())) {

            error(
                """
                    ${managedDeviceName.get()} has a device profile of ${hardwareProfile.get()}.
                    Wear, TV and Auto devices are presently not supported with Gradle Managed Devices.
                """.trimIndent()
            )
        }
    }

**Comment by alexvanyo** [comment]
Opened https://issuetracker.google.com/issues/232753500 as the tracking bug for Wear devices support.

**Comment by yschimke** [comment]
Moved to https://github.com/android/wear-os-samples/pull/708

**Pull request closed without merging**
