### PR TITLE
Update messaging sample tile

### PR DESCRIPTION
**Pull request by fstanis**
Update messaging sample in WearTilesKotlin to use tiles-material and use view binding in activity

### CODE REVIEW

**Comment by yschimke** [comment]
```
 > Task :app:compileDebugKotlin
w: /home/runner/work/wear-os-samples/wear-os-samples/WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileService.kt: (220, 9): Parameter 'deviceParameters' is never used

> Task :app:compileDebugJavaWithJavac

> Task :app:bundleDebugClasses
FAILURE: Build failed with an exception.
> Task :app:spotlessKotlinCheck FAILED

* What went wrong:
Execution failed for task ':app:spotlessKotlinCheck'.
> The following files had format violations:
      src/debug/java/com/example/wear/tiles/MainActivity.kt
          @@ -17,7 +17,6 @@
           
           import·android.content.ComponentName
           import·android.os.Bundle
          -import·android.widget.FrameLayout
           import·androidx.activity.ComponentActivity
           import·androidx.wear.tiles.manager.TileUiClient
           import·com.example.wear.tiles.databinding.ActivityMainBinding
  Run './gradlew :app:spotlessApply' to fix these violations.
```

**Comment by yschimke** [comment]
Does the sample image need an update?

https://github.com/android/wear-os-samples/tree/main/WearTilesKotlin

**Review by yschimke — APPROVED** [review]
Pending build fix

**Comment by fstanis** [comment]
Should be fixed now. I also updated the image even though the changes are minor visually.

**Pull request merged**
