### PR TITLE
Compose Advanced: Update dependencies

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Comment by shumelchyk** [comment]
For this and other PRs for updating dependencies - do we want to keep one version catalog on a root-level for all Wear OS samples for automation purposes or it doesn't needed?

**Comment by yschimke** [comment]
> For this and other PRs for updating dependencies - do we want to keep one version catalog on a root-level for all Wear OS samples for automation purposes or it doesn't needed?

I did previously, it doesn't work because the samples get imported to Android Studio as a single directory and must be self contained.

**Comment by yschimke** [comment]
@shumelchyk Going to land anyway, please let me know if you have concerns.  But I'll be testing this further in a draft PR.

**Comment by shumelchyk** [comment]
Ah I see, makes sense!

**Pull request merged**
