### PR TITLE
Removes 'Alpha' from watch face sample name.

### PR DESCRIPTION
**Pull request by codingjeremy**

### CODE REVIEW

**Review by alexvanyo — CHANGES_REQUESTED** [review]
The `ci` workflow will also need to be updated I'm guessing!

**Comment by codingjeremy** [comment]
Whoops, fixed!

**Comment by alexvanyo** [comment]
Oh and also the main `README` 😸

**Comment by codingjeremy** [comment]
Done.

**Review by alexvanyo — APPROVED** [review]

**Pull request merged**
