### PR TITLE
Renames to Complications

### PR DESCRIPTION
**Pull request by garanj**
Changes the name of the project to Complications, for simplicity.

### CODE REVIEW

**Comment by yschimke** [comment]
Is this an importable sample, will that be renamed?

**Comment by garanj** [comment]
> Is this an importable sample, will that be renamed?

Imported into g3?

**Comment by yschimke** [comment]
Android studio

**Comment by garanj** [comment]
> Android studio

Got it! Thanks!!

**Review by kul3r4 — APPROVED** [review]

**Pull request merged**
